"""initial

Revision ID: c0e5c4b6d9d9
Revises: 
Create Date: 2023-12-17 11:35:58.290573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e5c4b6d9d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('birthday', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint('char_length(name) >= 4'),
    sa.CheckConstraint('char_length(slug) >= 4'),
    sa.CheckConstraint('char_length(surname) >= 4'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('comics',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('volume', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('country', sa.VARCHAR(length=64), nullable=False),
    sa.CheckConstraint('char_length(country) >= 4'),
    sa.CheckConstraint('char_length(slug) >= 4'),
    sa.CheckConstraint('char_length(title) >= 4'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('universe',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.CheckConstraint('char_length(slug) >= 4'),
    sa.CheckConstraint('char_length(title) >= 2'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_created'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.CheckConstraint('char_length(name) >= 4'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('character',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), nullable=False),
    sa.Column('power', sa.VARCHAR(length=128), nullable=False),
    sa.Column('universe_id', sa.SMALLINT(), nullable=False),
    sa.Column('author_id', sa.SMALLINT(), nullable=False),
    sa.CheckConstraint('char_length(name) >= 2'),
    sa.CheckConstraint('char_length(power) >= 4'),
    sa.CheckConstraint('char_length(role) >= 4'),
    sa.CheckConstraint('char_length(slug) >= 4'),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_character_author_id'), 'character', ['author_id'], unique=False)
    op.create_index(op.f('ix_character_universe_id'), 'character', ['universe_id'], unique=False)
    op.create_table('comics_authors',
    sa.Column('comics_id', sa.SMALLINT(), nullable=False),
    sa.Column('author_id', sa.SMALLINT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['comics_id'], ['comics.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('comics_id', 'author_id', 'id')
    )
    op.create_index(op.f('ix_comics_authors_author_id'), 'comics_authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_comics_authors_comics_id'), 'comics_authors', ['comics_id'], unique=False)
    op.create_table('comics_characters',
    sa.Column('comics_id', sa.SMALLINT(), nullable=False),
    sa.Column('character_id', sa.SMALLINT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['comics_id'], ['comics.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('comics_id', 'character_id', 'id')
    )
    op.create_index(op.f('ix_comics_characters_character_id'), 'comics_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_comics_characters_comics_id'), 'comics_characters', ['comics_id'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('type_of_device', sa.VARCHAR(length=64), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('universe_id', sa.SMALLINT(), nullable=False),
    sa.Column('character_id', sa.SMALLINT(), nullable=False),
    sa.CheckConstraint('char_length(slug) >= 4'),
    sa.CheckConstraint('char_length(title) >= 4'),
    sa.CheckConstraint('char_length(type_of_device) >= 4'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_device_character_id'), 'device', ['character_id'], unique=False)
    op.create_index(op.f('ix_device_universe_id'), 'device', ['universe_id'], unique=False)
    op.create_table('sweet',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.SMALLINT(), nullable=False),
    sa.CheckConstraint('char_length(slug) >= 4'),
    sa.CheckConstraint('char_length(title) >= 4'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_sweet_character_id'), 'sweet', ['character_id'], unique=False)
    op.create_table('toy',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('type_of_toy', sa.VARCHAR(length=64), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('universe_id', sa.SMALLINT(), nullable=False),
    sa.Column('character_id', sa.SMALLINT(), nullable=False),
    sa.CheckConstraint('char_length(slug) >= 4'),
    sa.CheckConstraint('char_length(title) >= 4'),
    sa.CheckConstraint('char_length(type_of_toy) >= 4'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_toy_character_id'), 'toy', ['character_id'], unique=False)
    op.create_index(op.f('ix_toy_universe_id'), 'toy', ['universe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toy_universe_id'), table_name='toy')
    op.drop_index(op.f('ix_toy_character_id'), table_name='toy')
    op.drop_table('toy')
    op.drop_index(op.f('ix_sweet_character_id'), table_name='sweet')
    op.drop_table('sweet')
    op.drop_index(op.f('ix_device_universe_id'), table_name='device')
    op.drop_index(op.f('ix_device_character_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_comics_characters_comics_id'), table_name='comics_characters')
    op.drop_index(op.f('ix_comics_characters_character_id'), table_name='comics_characters')
    op.drop_table('comics_characters')
    op.drop_index(op.f('ix_comics_authors_comics_id'), table_name='comics_authors')
    op.drop_index(op.f('ix_comics_authors_author_id'), table_name='comics_authors')
    op.drop_table('comics_authors')
    op.drop_index(op.f('ix_character_universe_id'), table_name='character')
    op.drop_index(op.f('ix_character_author_id'), table_name='character')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('universe')
    op.drop_table('comics')
    op.drop_table('author')
    # ### end Alembic commands ###
